### ISSUE TITLE
About releases 

### ISSUE THREAD

**Issue by denar90** [nathanboktae/mocha-casperjs#74]
Hi. I was a bit confused when defined that version in `package.json` version `0.5.5` and in releases latest is `0.2.1`.I'm for example always looking versions in releases page.
Why not to update releases to latest? 
Thanks)

**Comment by nathanboktae** [comment]
> I'm for example always looking versions in releases page. Why not to update releases to latest?

Sure, but I'm pretty sure everyone uses [npm](https://www.npmjs.com/package/mocha-casperjs) because it's so awesome and easy to use (including for myself). But I have been lazy with my tagging so I'll start to fix that.

If you need to go back in time, look at the history of package.json to go back to a specifc version, or `npm install mocha-casperjs@<version>`

Why not use npm yourself?

**Comment by nathanboktae** [comment]
Though to be fair, there is no Node.js code here, so supporting other distribution mechanisms makes sense.

**Comment by denar90** [comment]
I'm using npm but sometimes I need to add deps by my hands. And I looking for a version in releases page)
